version: '3.8'

services:
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  frontend-vue:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    volumes:
      - ./api/src:/app/src

networks:
  default:
    driver: bridge

volumes:
  api-data: